SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `bicycles`;
DROP TABLE IF EXISTS `brands`;

CREATE TABLE `brands` (
`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(150) NOT NULL,
`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `bicycles` (
`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
`brandId` INT UNSIGNED NOT NULL,
`model` VARCHAR(150) NOT NULL,
`description` TEXT NULL,
`price` DECIMAL(10, 2) NOT NULL,
`stock` INT UNSIGNED NOT NULL DEFAULT 0,
`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT `fk_bicycles_brands`
FOREIGN KEY (`brandId`)
REFERENCES `brands` (`id`)
ON UPDATE CASCADE
ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;